### ISSUE TITLE
No link to xdg-mime, xdg-utils or freedesktop's bug tracker

### ISSUE THREAD

**Issue by forivall** [kevva/xdg-default-browser#1]
I quickly checked this out after seeing it on my activity feed, and tried it out, but it failed on my kde 5 installation. It's really a bug in either [xdg-utils](http://cgit.freedesktop.org/xdg/xdg-utils) (xdg-mime) or the tool within kde that xdg-mime calls (ktraderclient5) (which is where I filed a bug).

It would just be nice to see that, and deflect any bugs that might be upstream from you.

**Comment by sindresorhus** [comment]
:+1:

**Comment by kevva** [comment]
@forivall, could you submit a PR?
